### ISSUE TITLE
Uncaught TypeError: disposable.dispose is not a function

### ISSUE THREAD

**Issue by commonearth** [ayoubdev/atom-formatter-jsbeautify#1]
[Enter steps to reproduce below:]
1. ...Uninstall
2. ...

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-formatter-jsbeautify](https://github.com/ayoubdev/atom-formatter-jsbeautify) package, v1.1.2
### Stack Trace

Uncaught TypeError: disposable.dispose is not a function

```
At F:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25

TypeError: disposable.dispose is not a function
    at F:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25:29
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (F:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24:26)
    at F:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25:29
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (F:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24:26)
    at Provider.module.exports.Provider.destroy (F:\Program Files\Atom\resources\app.asar\node_modules\service-hub\lib\provider.js:42:39)
    at Disposable.disposalAction (F:\Program Files\Atom\resources\app.asar\node_modules\service-hub\lib\service-hub.js:36:20)
    at Disposable.module.exports.Disposable.dispose (F:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\disposable.js:26:16)
    at F:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25:29
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (F:\Program Files\Atom\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24:26)
    at Package.module.exports.Package.deactivateResources (F:\Program Files\Atom\resources\app.asar\src\package.js:674:15)
    at Package.module.exports.Package.deactivate (F:\Program Files\Atom\resources\app.asar\src\package.js:635:12)
    at PackageManager.module.exports.PackageManager.deactivatePackage (F:\Program Files\Atom\resources\app.asar\src\package-manager.js:622:12)
    at PackageManager.module.exports.PackageManager.uninstall (F:\Program Files\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:481:23)
    at PackageCard.module.exports.PackageCard.uninstall (F:\Program Files\Atom\resources\app.asar\node_modules\settings-view\lib\package-card.js:717:34)
    at HTMLButtonElement.<anonymous> (F:\Program Files\Atom\resources\app.asar\node_modules\settings-view\lib\package-card.js:302:24)
    at HTMLButtonElement.jQuery.event.dispatch (F:\Program Files\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (F:\Program Files\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```
### Commands

```
     -0:06.3.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-formatter-jsbeautify, v1.1.2
emmet, v2.4.3
flexbox-snippets, v0.3.0
formatter, v2.12.3
language-postcss, v1.2.0
linter, v1.11.4
open-in-browsers, v0.0.15
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by adbayb** [comment]
Hello @commonearth ,

It's not related to atom-formatter-jsbeautify itself. This error may occur when you try to update some existing packages. See (https://github.com/atom/settings-view/issues/656)

Just try to uninstall, reinstall package.
