### ISSUE TITLE
Failed to activate the atom-formatter-jsbeautify package

### ISSUE THREAD

**Issue by GenieTim** [ayoubdev/atom-formatter-jsbeautify#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-formatter-jsbeautify](https://github.com/ayoubdev/atom-formatter-jsbeautify) package 1.1.2

### Stack Trace

Failed to activate the atom-formatter-jsbeautify package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Module.consumeFormatter (/packages/formatter/lib/main.coffee:70:21)
    at Provider.module.exports.Provider.provide (/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/app.asar/src/package.js:396:71)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:221:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:352:19
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/app.asar/src/package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/app.asar/src/package-manager.js:173:14)
    at /app.asar/node_modules/settings-view/lib/package-card.js:348:27)
    at HTMLButtonElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:02.0 core:copy (div.package-readme.native-key-bindings)
     -2:58.3.0 refactor:done (input.hidden-input)
     -2:58.3.0 editor:newline (input.hidden-input)
     -2:58.1.0 core:paste (input.hidden-input)
     -2:40 core:save (input.hidden-input)
     -2:31 formatter:format-code (input.hidden-input)
     -2:20.2.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
  3x -1:40.8.0 core:backspace (input.hidden-input)
     -1:20.3.0 core:save (input.hidden-input)
  2x -1:17.2.0 formatter:format-code (input.hidden-input)
     -0:25.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.0 
atom-formatter-jsbeautify 1.1.2 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-symfony2 0.2.1 
beacon-ui 0.5.0 
formatter 2.12.3 
git-plus 7.2.2 
intentions 1.1.2 
markdown-format 2.5.1 
php-integrator-refactoring 1.3.1 
php-twig 4.0.0 
refactor 0.11.3 
```

**Comment by GenieTim** [comment]
Maybe related to [https://github.com/atom-community/formatter/issues/7](https://github.com/atom-community/formatter/issues/7)?
